service: hello-slack-apps
frameworkVersion: '2 || 3'

provider:
  name: aws
  runtime: python3.8
  region: eu-west-1
  logRetentionInDays: 5
  lambdaHashingVersion: '20201221'

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get
      - httpApi:
          path: /
          method: post
